# Generated by Django 5.0.3 on 2024-04-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('search_query', models.CharField(max_length=100)),
                ('search_timestamp', models.DateTimeField(auto_now_add=True)),
                ('search_data', models.JSONField()),
            ],
        ),
    ]
